name: Build & Push Go Webserver with Docker Compose

on:
  push:
    branches:
      - main  # Triggers when changes are pushed to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image using Docker Compose
        run: |
          docker-compose build
          docker-compose push

      - name: Logout from Docker Hub
        run: docker logout






# name: Build and Push Go Webserver

# on:
#   push:
#     branches:
#       - main101  # Trigger when changes are pushed to main

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: '1.21'  # Adjust to your Go version

#       - name: Build Go Webserver
#         run: |
#           go mod tidy
#           go build -o app .

#       - name: Log in to Docker Hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#       - name: Build Docker Image
#         run: |
#           docker build -t mydockerhubuser/myapp:${{ github.sha }} .
#           docker tag mydockerhubuser/myapp:${{ github.sha }} mydockerhubuser/myapp:latest

#       - name: Push Docker Image
#         run: |
#           docker push mydockerhubuser/myapp:${{ github.sha }}
#           docker push mydockerhubuser/myapp:latest
